use_frameworks!

platform :ios, '9.0'

target 'BTestDemo_Example' do
  pod 'BTestDemo', :path => '../'

  target 'BTestDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
